/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 992465158970983deeaa28577ddfb5f3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		SCENARIOFORGE_DB: D1Database;
		ASSETS: Fetcher;
		AUTH_SECRET_KEY: string;
		GITHUB_APP_ID: string;
		GITHUB_APP_PRIVATE_KEY: string;
		GITHUB_APP_SLUG: string;
		GITHUB_APP_INSTALL_URL: string;
		CODEX_AUTH_BRIDGE_URL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_SECRET_KEY" | "GITHUB_APP_ID" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_APP_SLUG" | "GITHUB_APP_INSTALL_URL" | "CODEX_AUTH_BRIDGE_URL">> {}
}
